# Generated by Django 6.0.3 on 2026-04-06 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LINKEDIN', 'LinkedIn (Friendly)'), ('INVESTOR', 'Investor Relations (Professional)'), ('SUPPORT', 'Support Docs (Clarity)')], max_length=50, unique=True)),
                ('min_polarity', models.FloatField(default=0.1)),
                ('max_subjectivity', models.FloatField(default=0.5)),
                ('min_formality_score', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='ContentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('final_polarity', models.FloatField()),
                ('final_subjectivity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona_applied', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.brandpersona')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BrandPreset',
        ),
    ]
