# Generated by Django 6.0.3 on 2026-04-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('linkedin', 'LinkedIn'), ('investor_relations', 'Investor Relations'), ('support_docs', 'Support Documentation')], max_length=50)),
                ('min_professionalism', models.FloatField(default=0.5)),
                ('max_professionalism', models.FloatField(default=0.9)),
                ('min_friendliness', models.FloatField(default=0.3)),
                ('max_friendliness', models.FloatField(default=0.7)),
                ('min_clarity', models.FloatField(default=0.6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand Persona',
                'verbose_name_plural': 'Brand Personas',
                'ordering': ['-created_at'],
            },
        ),
    ]
