# Generated by Django 6.0.3 on 2026-04-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('target_polarity', models.FloatField(default=0.0)),
                ('target_subjectivity', models.FloatField(default=0.5)),
                ('target_formality', models.FloatField(default=0.5)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
